version: 1.0.{build}

environment:
  nugetKey:
    secure: CRRgxp0YT0nwHJ2juNykbOeJVs88vQYh3tmA0gITjcfFOa3PMJ4W0DC8vTjLXHeQ
    
before_build:
  - nuget restore src/CSharpHDF5/CSharpHDF5.sln
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;C:\\projects\\csharphdf5\\src\\CSharpHDF5\\packages\\HDF.PInvoke.1.8.16.11\\lib\\native\\bin64\\;%PATH%"
    
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - src/packages -> **\packages.config   

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

platform: x64

configuration: Debug
  
build:
  project: src/CSharpHDF5/CSharpHDF5.sln
  verbosity: Minimal 
  publish_nuget: true
 
after_test: 
    - c:\projects\csharphdf5\src\CSharpHDF5\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"c:\projects\csharphdf5\src\CSharpHDF5\packages\NUnit.ConsoleRunner.3.2.0\tools\nunit3-console.exe" -targetargs:"/noresults /noisolation /testcontainer:""c:\projects\csharphdf5\src\CSharpHDF5Tests\bin\x64\Debug\CSharpHDF5Tests.dll" -filter:"+[CSharpHDF5]*  -[CSharpHDF5]CSharpHDF5.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:c:\projects\csharphdf5_coverage.xml
    - pip install codecov
    - codecov -f "c:\projects\csharphdf5_coverage.xml"
 
deploy:
  provider: NuGet
  api_key:  nugetKey
  skip_symbols: true
  artifact: /.*\.nupkg/  
  on:
    branch: master
    platform: x64
    appveyor_repo_tag: true